# Site settings
title: NXT-PLUS
email: incentivetoken@gmail.com
github_repo: https://github.com/fimkrypto/nxt-plus
description: >
  NXT-PLUS showcases the strength of the NXT platform and it's community.<br>
  NXT by design was intented to be extended by third-party developers.<br>
  NXT-PLUS is fully compatible with NXT while adding new and powerfull extensions to the protocol.
baseurl: "/nxt-plus-site"
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  fimkrypto

# Build settings
markdown: kramdown

nxt_version: 1.4.16
